Integrated header
tabuckner/broskichat pull request #6
Opened 2018-07-31 06:54 UTC by akeon-lee

1) Implemented the header component
      - /src/Components/Partials
2) Implemented really simple testing that checks the value of a variable called logoTitle

2018-07-31 16:59 UTC, tabuckner commented
@akeon-lee Hey man, you had some merge conflicts that i took care of. They were most likely related to the changes we made last night. Leaving my review comments now!

2018-07-31 17:07 UTC, tabuckner requested changes
Overall, you did a great job man!! A couple of small comments that are just style consistency things. 

To make the changes, pull down the latest version of the branch in the remote repo, make your changes, stage/commit them, and the push back up. Travis build will re-run and I'll take a look again tonight. Feel free to @mention me or send me a message on slack homie 💯

2018-07-31 17:07 UTC, tabuckner commented on broskichat-app/src/App.test.js
> +describe('<Header />', () => {
@akeon-lee nice job adding a test assertion here! We'll probably move these to individual files in the future if it gets too long.

2018-07-31 17:07 UTC, tabuckner commented on broskichat-app/src/Components/Partials/Header.js
> +                        {/* If annonymous */}
@akeon-lee great foresight here man!

2018-07-31 17:07 UTC, tabuckner commented on broskichat-app/src/App.jsx
> +
@akeon-lee we should remove this extra space

2018-07-31 17:07 UTC, tabuckner commented on broskichat-app/src/App.css
> +  background-color: #333;
I see a theme forming! Once the theme fills out a little more, we'll want to override the bulma sass variables. This is fine for now though 👍

2018-07-31 17:07 UTC, tabuckner commented on broskichat-app/src/Components/Partials/Header.js
> +class Header extends React.Component {
@akeon-lee lets try to be consistent with our file formatting. We should use the .jsx extension and 2 spaces instead of 4.

2018-08-01 00:03 UTC, tabuckner approved these changes

2018-08-01 00:04 UTC, tabuckner commented
@akeon-lee nice man -- lookin good! when you get a sec:
- Squash and Merge
- Delete Branch on Remote Repo
- Move the ticket from To-Build to Done! 
- Party

2018-08-02 04:01 UTC, Renestl approved these changes
Looks good!

2018-08-03 00:00 UTC, tabuckner commented
@akeon-lee Hey man, are we gonna merge this or what? :boom:

2018-08-03 00:03 UTC, merged

2018-08-03 00:03 UTC, akeon-lee commented
Whoops, sorry for the delay. Just squashed and merged it.